/*
  Heavily inspired from envycontrol.
  Thank you bayasdev for making optimus easier.
  Credit: https://github.com/bayasdev/envycontrol
*/

#ifndef OPTIMUS_HH
#define OPTIMUS_HH

#include <iostream>
#include <string>
#include <unistd.h>
#include <sys/stat.h>
#include <cstring>
#include <cstdio>

class OptimusSwitch {
public:
  static constexpr const char* BLACKLIST_PATH =       "/etc/modprobe.d/blacklist-nvidia.conf";
  static constexpr const char* UDEV_INTEGRATED_PATH = "/etc/udev/rules.d/50-remove-nvidia.rules";
  static constexpr const char* UDEV_PM_PATH =         "/etc/udev/rules.d/80-nvidia-pm.rules";
  static constexpr const char* XORG_PATH =            "/etc/X11/xorg.conf";
  static constexpr const char* EXTRA_XORG_PATH =      "/etc/X11/xorg.conf.d/10-nvidia.conf";
  static constexpr const char* MODESET_PATH =         "/etc/modprobe.d/nvidia.conf";
  static constexpr const char* SDDM_XSETUP_PATH =     "/usr/share/sddm/scripts/Xsetup";
  static constexpr const char* SDDM_XSETUP_BAK_PATH = "/usr/share/sddm/scripts/Xsetup.bak";
  static constexpr const char* LIGHTDM_SCRIPT_PATH =  "/etc/lightdm/nvidia.sh";
  static constexpr const char* LIGHTDM_CONFIG_PATH =  "/etc/lightdm/lightdm.conf.d/20-nvidia.conf";
  static constexpr const char* LEGACY_XORG_PATH =     "/etc/X11/xorg.conf.d/90-nvidia.conf";
  static constexpr const char* LEGACY_UDEV_RM_PATH =  "/lib/udev/rules.d/50-remove-nvidia.rules";
  static constexpr const char* LEGACY_UDEV_PM_PATH =  "/lib/udev/rules.d/80-nvidia-pm.rules";

  static constexpr const char* UDEV_INTEGRATED_CONTENT =
	"# Automatically generated by gpu_mode\n"
	"\n"
	"# Remove NVIDIA USB xHCI Host Controller devices, if present\n"
	"ACTION==\"add\", SUBSYSTEM==\"pci\", ATTR{vendor}==\"0x10de\", ATTR{class}==\"0x0c0330\", ATTR{power/control}=\"auto\", ATTR{remove}=\"1\"\n"
	"\n"
	"# Remove NVIDIA USB Type-C UCSI devices, if present\n"
	"ACTION==\"add\", SUBSYSTEM==\"pci\", ATTR{vendor}==\"0x10de\", ATTR{class}==\"0x0c8000\", ATTR{power/control}=\"auto\", ATTR{remove}=\"1\"\n"
	"\n"
	"# Remove NVIDIA Audio devices, if present\n"
	"ACTION==\"add\", SUBSYSTEM==\"pci\", ATTR{vendor}==\"0x10de\", ATTR{class}==\"0x040300\", ATTR{power/control}=\"auto\", ATTR{remove}=\"1\"\n"
	"\n"
	"# Remove NVIDIA VGA/3D controller devices\n"
	"ACTION==\"add\", SUBSYSTEM==\"pci\", ATTR{vendor}==\"0x10de\", ATTR{class}==\"0x03[0-9]*\", ATTR{power/control}=\"auto\", ATTR{remove}=\"1\"\n";

	static constexpr const char* MODESET_CONTENT =
	"# Automatically generated by gpu_mode\n"
	"\n"
	"options nvidia-drm modeset=1\n"
	"options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0\n";

	static constexpr const char* XORG_INTEL_TEMPLATE =
	"# Automatically generated by gpu_mode\n"
	"\n"
	"Section \"ServerLayout\"\n"
	"    Identifier \"layout\"\n"
	"    Screen 0 \"nvidia\"\n"
	"    Inactive \"intel\"\n"
	"EndSection\n"
	"\n"
	"Section \"Device\"\n"
	"    Identifier \"nvidia\"\n"
	"    Driver \"nvidia\"\n"
	"    BusID \"%s\"\n"
	"EndSection\n"
	"\n"
	"Section \"Screen\"\n"
	"    Identifier \"nvidia\"\n"
	"    Device \"nvidia\"\n"
	"    Option \"AllowEmptyInitialConfiguration\"\n"
	"EndSection\n"
	"\n"
	"Section \"Device\"\n"
	"    Identifier \"intel\"\n"
	"    Driver \"modesetting\"\n"
	"EndSection\n"
	"\n"
	"Section \"Screen\"\n"
	"    Identifier \"intel\"\n"
	"    Device \"intel\"\n"
	"EndSection\n";

	static constexpr const char* LIGHTDM_CONFIG_CONTENT =
	"# Automatically generated by gpu_mode\n"
	"\n"
	"[Seat:*]\n"
	"display-setup-script=/etc/lightdm/nvidia.sh\n";

	static constexpr const char* XRANDR_SCRIPT_TEMPLATE =
	"#!/bin/sh\n"
	"# Automatically generated by gpu_mode\n"
	"\n"
	"current=\"\"\n"
	"\n"
	"xrandr --setprovideroutputsource \"%s\" NVIDIA-0\n"
	"xrandr --auto\n"
	"\n"
	"for next in $(xrandr --listmonitors | grep -E \" *[0-9]+:.*\" | cut -d\" \" -f6); do\n"
	"  [ -z \"$current\" ] && current=$next && continue\n"
	"  xrandr --output \"$current\" --auto --output \"$next\" --auto --right-of \"$current\"\n"
	"  current=$next\n"
	"done\n";

	static constexpr const char *BLACKLIST_CONTENT =
  "# Automatically generated by gpu_mode\n"
  "\n"
  "blacklist nouveau\n"
  "blacklist nvidia\n"
  "blacklist nvidia_drm\n"
  "blacklist nvidia_uvm\n"
  "blacklist nvidia_modeset\n"
  "alias nouveau off\n"
  "alias nvidia off\n"
  "alias nvidia_drm off\n"
  "alias nvidia_uvm off\n"
  "alias nvidia_modeset off\n";

	void switch_to_igpu(void);
	void write_file(const char *path, const char *content, bool exec = false);
	void cleanup(void);
	void rebuild_initramfs(void);
	void optimus_remove(const char* path);
	void edit_sddm(void);
	void switch_to_dgpu(void);
	void switch_gpus(bool k);

	bool get_nvidia_pci_bus(char *out, size_t outlen);

	char *get_display_manager(void);
};

#endif
